set_block_operator

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -172,8 +172,8 @@ jobs:
             - name: Build
               shell: bash -l {0}
               run: |
-                  # cmake --build build --target all --parallel 2
-                  cmake --build build --target finite-volume-lid-driven-cavity
+                  cmake --build build --target all --parallel 2
+                  # cmake --build build --target finite-volume-lid-driven-cavity
 
             # - name: Test with googletest
             #   shell: bash -l {0}
@@ -388,178 +388,178 @@ jobs:
     # CHECK_NAN
     #
     #########################################################
-    # linux-mamba-check-nan:
-    #     needs: [pre-commit, cppcheck]
-    #     runs-on: ubuntu-latest
-    #     steps:
-    #         - uses: actions/checkout@v4
+    linux-mamba-check-nan:
+        needs: [pre-commit, cppcheck]
+        runs-on: ubuntu-latest
+        steps:
+            - uses: actions/checkout@v4
 
-    #         - name: Cache
-    #           uses: actions/cache@v4
-    #           with:
-    #               path: |
-    #                   ~/.cache/ccache
-    #                   ~/micromamba-root/envs/samurai-env
-    #               key: linux-mamba-check-nan
-    #               restore-keys: |
-    #                   linux-mamba-check-nan
+            - name: Cache
+              uses: actions/cache@v4
+              with:
+                  path: |
+                      ~/.cache/ccache
+                      ~/micromamba-root/envs/samurai-env
+                  key: linux-mamba-check-nan
+                  restore-keys: |
+                      linux-mamba-check-nan
 
-    #         - name: Mamba and samurai env installation
-    #           uses: mamba-org/setup-micromamba@v2
-    #           with:
-    #               environment-file: conda/environment.yml
-    #               environment-name: samurai-env
-    #               cache-environment: true
+            - name: Mamba and samurai env installation
+              uses: mamba-org/setup-micromamba@v2
+              with:
+                  environment-file: conda/environment.yml
+                  environment-name: samurai-env
+                  cache-environment: true
 
-    #         - name: Petsc installation
-    #           shell: bash -l {0}
-    #           run: |
-    #               conda install -y petsc pkg-config cxx-compiler
+            - name: Petsc installation
+              shell: bash -l {0}
+              run: |
+                  conda install -y petsc pkg-config cxx-compiler
 
-    #         - name: Conda informations
-    #           shell: bash -l {0}
-    #           run: |
-    #               conda info
-    #               conda list
+            - name: Conda informations
+              shell: bash -l {0}
+              run: |
+                  conda info
+                  conda list
 
-    #         - name: Configure
-    #           shell: bash -l {0}
-    #           run: |
-    #               cmake \
-    #                   . \
-    #                   -Bbuild \
-    #                   -GNinja \
-    #                   -DCMAKE_BUILD_TYPE=Debug \
-    #                   -DSAMURAI_CHECK_NAN=ON \
-    #                   -DWITH_PETSC=ON \
-    #                   -DBUILD_DEMOS=ON
+            - name: Configure
+              shell: bash -l {0}
+              run: |
+                  cmake \
+                      . \
+                      -Bbuild \
+                      -GNinja \
+                      -DCMAKE_BUILD_TYPE=Debug \
+                      -DSAMURAI_CHECK_NAN=ON \
+                      -DWITH_PETSC=ON \
+                      -DBUILD_DEMOS=ON
 
-    #         - name: Build
-    #           shell: bash -l {0}
-    #           run: |
-    #               cmake --build build --target finite-volume-burgers
-    #               cmake --build build --target finite-volume-lid-driven-cavity
+            - name: Build
+              shell: bash -l {0}
+              run: |
+                  cmake --build build --target finite-volume-burgers
+                  cmake --build build --target finite-volume-lid-driven-cavity
 
-    #         - name: test finite-volume-burgers
-    #           shell: bash -l {0}
-    #           run: |
-    #               cd build
-    #               set -e  # Stop on first failure
-    #               ./demos/FiniteVolume/finite-volume-burgers --min-level 2 --max-level 6
+            - name: test finite-volume-burgers
+              shell: bash -l {0}
+              run: |
+                  cd build
+                  set -e  # Stop on first failure
+                  ./demos/FiniteVolume/finite-volume-burgers --min-level 2 --max-level 6
 
-    #         - name: test finite-volume-lid-driven-cavity
-    #           shell: bash -l {0}
-    #           run: |
-    #               cd build
-    #               set -e  # Stop on first failure
-    #               ./demos/FiniteVolume/finite-volume-lid-driven-cavity --min-level 3 --max-level 6
+            - name: test finite-volume-lid-driven-cavity
+              shell: bash -l {0}
+              run: |
+                  cd build
+                  set -e  # Stop on first failure
+                  ./demos/FiniteVolume/finite-volume-lid-driven-cavity --min-level 3 --max-level 6
 
     #
     # MPI with CHECK_NAN
     #
     #########################################################
-    # linux-mamba-check-nan-mpi:
-    #     needs: [pre-commit, cppcheck]
-    #     runs-on: ubuntu-latest
-    #     steps:
-    #         - uses: actions/checkout@v4
+    linux-mamba-check-nan-mpi:
+        needs: [pre-commit, cppcheck]
+        runs-on: ubuntu-latest
+        steps:
+            - uses: actions/checkout@v4
 
-    #         - name: Cache
-    #           uses: actions/cache@v4
-    #           with:
-    #               path: |
-    #                   ~/.cache/ccache
-    #                   ~/micromamba-root/envs/samurai-env
-    #               key: linux-mamba-check-nan-mpi
-    #               restore-keys: |
-    #                   linux-mamba-check-nan-mpi
+            - name: Cache
+              uses: actions/cache@v4
+              with:
+                  path: |
+                      ~/.cache/ccache
+                      ~/micromamba-root/envs/samurai-env
+                  key: linux-mamba-check-nan-mpi
+                  restore-keys: |
+                      linux-mamba-check-nan-mpi
 
-    #         - name: Mamba and samurai env installation
-    #           uses: mamba-org/setup-micromamba@v2
-    #           with:
-    #               environment-file: conda/mpi-environment.yml
-    #               environment-name: samurai-env
-    #               cache-environment: true
+            - name: Mamba and samurai env installation
+              uses: mamba-org/setup-micromamba@v2
+              with:
+                  environment-file: conda/mpi-environment.yml
+                  environment-name: samurai-env
+                  cache-environment: true
 
-    #         - name: Petsc installation
-    #           shell: bash -l {0}
-    #           run: |
-    #               conda install -y petsc pkg-config cxx-compiler
+            - name: Petsc installation
+              shell: bash -l {0}
+              run: |
+                  conda install -y petsc pkg-config cxx-compiler
 
-    #         - name: Conda informations
-    #           shell: bash -l {0}
-    #           run: |
-    #               conda info
-    #               conda list
+            - name: Conda informations
+              shell: bash -l {0}
+              run: |
+                  conda info
+                  conda list
 
-    #         - name: Configure
-    #           shell: bash -l {0}
-    #           run: |
-    #               cmake \
-    #                   . \
-    #                   -Bbuild \
-    #                   -GNinja \
-    #                   -DWITH_MPI=ON \
-    #                   -DCMAKE_BUILD_TYPE=Debug \
-    #                   -DSAMURAI_CHECK_NAN=ON \
-    #                   -DBUILD_DEMOS=ON
+            - name: Configure
+              shell: bash -l {0}
+              run: |
+                  cmake \
+                      . \
+                      -Bbuild \
+                      -GNinja \
+                      -DWITH_MPI=ON \
+                      -DCMAKE_BUILD_TYPE=Debug \
+                      -DSAMURAI_CHECK_NAN=ON \
+                      -DBUILD_DEMOS=ON
 
-    #         - name: Build
-    #           shell: bash -l {0}
-    #           run: |
-    #               cmake --build build --target finite-volume-advection-2d
-    #               cmake --build build --target finite-volume-burgers
+            - name: Build
+              shell: bash -l {0}
+              run: |
+                  cmake --build build --target finite-volume-advection-2d
+                  cmake --build build --target finite-volume-burgers
 
-    #         - name: test finite-volume-advection-2d
-    #           shell: bash -l {0}
-    #           run: |
-    #               cd build
-    #               set -e  # Stop on first failure
-    #               mpiexec -n 1 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.05 --nfiles 1
-    #               mpiexec -n 2 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.05 --nfiles 1
-    #               mpiexec -n 3 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.05 --nfiles 1
+            - name: test finite-volume-advection-2d
+              shell: bash -l {0}
+              run: |
+                  cd build
+                  set -e  # Stop on first failure
+                  mpiexec -n 1 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.05 --nfiles 1
+                  mpiexec -n 2 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.05 --nfiles 1
+                  mpiexec -n 3 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.05 --nfiles 1
 
-    #         - name: test finite-volume-burgers
-    #           shell: bash -l {0}
-    #           run: |
-    #               cd build
-    #               set -e  # Stop on first failure
-    #               mpiexec -n 1 ./demos/FiniteVolume/finite-volume-burgers --Tf 0.1 --nfiles 1 --max-level 8
-    #               mpiexec -n 2 ./demos/FiniteVolume/finite-volume-burgers --Tf 0.1 --nfiles 1 --max-level 8
-    #               # This test is failing with 3 processes due to a bug in the exchange of subdomain corners
-    #               # mpiexec -n 3 ./demos/FiniteVolume/finite-volume-burgers --Tf 0.1 --nfiles 1 --max-level 8
+            - name: test finite-volume-burgers
+              shell: bash -l {0}
+              run: |
+                  cd build
+                  set -e  # Stop on first failure
+                  mpiexec -n 1 ./demos/FiniteVolume/finite-volume-burgers --Tf 0.1 --nfiles 1 --max-level 8
+                  mpiexec -n 2 ./demos/FiniteVolume/finite-volume-burgers --Tf 0.1 --nfiles 1 --max-level 8
+                  # This test is failing with 3 processes due to a bug in the exchange of subdomain corners
+                  # mpiexec -n 3 ./demos/FiniteVolume/finite-volume-burgers --Tf 0.1 --nfiles 1 --max-level 8
 
     #
     # Compile snippets in documentation
     #
     #########################################################
-    # compile_snippets:
-    #     needs: [pre-commit, cppcheck]
-    #     runs-on: ubuntu-latest
-    #     steps:
-    #         - uses: actions/checkout@v4
+    compile_snippets:
+        needs: [pre-commit, cppcheck]
+        runs-on: ubuntu-latest
+        steps:
+            - uses: actions/checkout@v4
 
-    #         - name: Mamba and samurai env installation
-    #           uses: mamba-org/setup-micromamba@v2
-    #           with:
-    #               environment-file: conda/environment.yml
-    #               environment-name: samurai-env
-    #               cache-environment: true
+            - name: Mamba and samurai env installation
+              uses: mamba-org/setup-micromamba@v2
+              with:
+                  environment-file: conda/environment.yml
+                  environment-name: samurai-env
+                  cache-environment: true
 
-    #         - name: Compiler installation
-    #           shell: bash -l {0}
-    #           run: |
-    #               micromamba install -y cxx-compiler
+            - name: Compiler installation
+              shell: bash -l {0}
+              run: |
+                  micromamba install -y cxx-compiler
 
-    #         - name: Configure
-    #           shell: bash -l {0}
-    #           run: |
-    #               cmake \
-    #                   . \
-    #                   -Bbuild \
-    #                   -DBUILD_SNIPPETS=ON
+            - name: Configure
+              shell: bash -l {0}
+              run: |
+                  cmake \
+                      . \
+                      -Bbuild \
+                      -DBUILD_SNIPPETS=ON
 
-    #         - name: Build snippets
-    #           shell: bash -l {0}
-    #           run: |
-    #               cmake --build build --target all --parallel 4
+            - name: Build snippets
+              shell: bash -l {0}
+              run: |
+                  cmake --build build --target all --parallel 4
