Add obstacle test in CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -404,8 +404,8 @@ jobs:
             - name: Build
               shell: bash -l {0}
               run: |
-                  cmake --build build --target finite-volume-burgers --parallel 4
-                  cmake --build build --target finite-volume-lid-driven-cavity --parallel 4
+                  cmake --build build --target finite-volume-burgers
+                  cmake --build build --target finite-volume-lid-driven-cavity
 
             - name: test finite-volume-burgers
               shell: bash -l {0}
@@ -420,3 +420,73 @@ jobs:
                   cd build
                   set -e  # Stop on first failure
                   ./demos/FiniteVolume/finite-volume-lid-driven-cavity --min-level 3 --max-level 6
+
+    linux-mamba-check-nan-mpi:
+        needs: [pre-commit, cppcheck]
+        runs-on: ubuntu-latest
+        steps:
+            - uses: actions/checkout@v4
+
+            - name: Cache
+              uses: actions/cache@v4
+              with:
+                  path: |
+                      ~/.cache/ccache
+                      ~/micromamba-root/envs/samurai-env
+                  key: linux-mamba-check-nan
+                  restore-keys: |
+                      linux-mamba-check-nan
+
+            - name: Mamba and samurai env installation
+              uses: mamba-org/setup-micromamba@v2
+              with:
+                  environment-file: conda/mpi-environment.yml
+                  environment-name: samurai-env
+                  cache-environment: true
+
+            - name: Petsc installation
+              shell: bash -l {0}
+              run: |
+                  conda install -y petsc pkg-config cxx-compiler
+
+            - name: Conda informations
+              shell: bash -l {0}
+              run: |
+                  conda info
+                  conda list
+
+            - name: Configure
+              shell: bash -l {0}
+              run: |
+                  cmake \
+                      . \
+                      -Bbuild \
+                      -GNinja \
+                      -DWITH_MPI=ON \
+                      -DCMAKE_BUILD_TYPE=Debug \
+                      -DSAMURAI_CHECK_NAN=ON \
+                      -DBUILD_DEMOS=ON
+
+            - name: Build
+              shell: bash -l {0}
+              run: |
+                  cmake --build build --target finite-volume-advection-2d
+                  cmake --build build --target finite-volume-burgers
+
+            - name: test finite-volume-advection-2d
+              shell: bash -l {0}
+              run: |
+                  cd build
+                  set -e  # Stop on first failure
+                  mpiexec -n 1 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.05
+                  mpiexec -n 2 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.05
+                  mpiexec -n 3 ./demos/FiniteVolume/finite-volume-advection-2d --Tf 0.05
+
+            - name: test finite-volume-burgers
+              shell: bash -l {0}
+              run: |
+                  cd build
+                  set -e  # Stop on first failure
+                  mpiexec -n 1 ./demos/FiniteVolume/finite-volume-burgers --Tf 0.1 --nfiles 20 --max-level 8
+                  mpiexec -n 2 ./demos/FiniteVolume/finite-volume-burgers --Tf 0.1 --nfiles 20 --max-level 8
+                  mpiexec -n 3 ./demos/FiniteVolume/finite-volume-burgers --Tf 0.1 --nfiles 20 --max-level 8
