Try to fix CI with superlu

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -296,27 +296,27 @@ jobs:
                   GLIBC_TUNABLES: "glibc.malloc.tcache_count=0"
               run: |
                   cd build
-                  set -e  # Stop on first failure
+                  # set -e  # Stop on first failure
                   # The MUMPS conda package is compiled with OpenMP. We set the number of threads to 1 to have deterministic output.
-                  export OMP_NUM_THREADS=1
-                  mpiexec -n 1 ./demos/FiniteVolume/finite-volume-heat --init-sol crenel -pc_type lu --Tf 0.1 --max-level 8
-                  mpiexec -n 2 ./demos/FiniteVolume/finite-volume-heat --init-sol crenel -pc_type lu --Tf 0.1 --max-level 8
-                  mpiexec -n 3 ./demos/FiniteVolume/finite-volume-heat --init-sol crenel -pc_type lu --Tf 0.1 --max-level 8
+                  # export OMP_NUM_THREADS=1
+                  mpiexec -n 1 ./demos/FiniteVolume/finite-volume-heat --init-sol crenel -pc_type lu -pc_factor_mat_solver_type superlu_dist --Tf 0.1 --max-level 8
+                  mpiexec -n 2 ./demos/FiniteVolume/finite-volume-heat --init-sol crenel -pc_type lu -pc_factor_mat_solver_type superlu_dist --Tf 0.1 --max-level 8
+                  mpiexec -n 3 ./demos/FiniteVolume/finite-volume-heat --init-sol crenel -pc_type lu -pc_factor_mat_solver_type superlu_dist --Tf 0.1 --max-level 8
                   ls
                   python ../python/compare.py heat_2D_size_1_ite_ heat_2D_size_2_ite_ --start 1 --end 9 --tol 1e-14
-                  python ../python/compare.py heat_2D_size_1_ite_ heat_2D_size_3_ite_ --start 1 --end 9 --tol 1e-5 # Less strict tolerance needed due to bugs in the mesh?
+                  python ../python/compare.py heat_2D_size_1_ite_ heat_2D_size_3_ite_ --start 1 --end 9 --tol 1e-14 # 1e-5 Less strict tolerance needed due to bugs in the mesh?
 
             - name: MPI test finite-volume-lid-driven-cavity
               shell: bash -l {0}
               run: |
                   cd build
-                  set -e  # Stop on first failure
+                  # set -e  # Stop on first failure
                   # The MUMPS conda package is compiled with OpenMP. We set the number of threads to 1 to have deterministic output.
-                  export OMP_NUM_THREADS=1
-                  mpiexec -n 1 ./demos/FiniteVolume/finite-volume-lid-driven-cavity --filename ldc_ink_size_1 --Tf 0.1 --nfiles 1 --min-level 8 --max-level 8
-                  mpiexec -n 2 ./demos/FiniteVolume/finite-volume-lid-driven-cavity --filename ldc_ink_size_2 --Tf 0.1 --nfiles 1 --min-level 8 --max-level 8
+                  # export OMP_NUM_THREADS=1
+                  mpiexec -n 1 ./demos/FiniteVolume/finite-volume-lid-driven-cavity -pc_type lu -pc_factor_mat_solver_type superlu_dist --filename ldc_ink_size_1 --Tf 0.1 --nfiles 1 --min-level 8 --max-level 8
+                  mpiexec -n 2 ./demos/FiniteVolume/finite-volume-lid-driven-cavity -pc_type lu -pc_factor_mat_solver_type superlu_dist --filename ldc_ink_size_2 --Tf 0.1 --nfiles 1 --min-level 8 --max-level 8
                   ls
-                  python ../python/compare.py ldc_ink_size_1 ldc_ink_size_2 --tol 1e-11
+                  python ../python/compare.py ldc_ink_size_1 ldc_ink_size_2 --tol 1e-14
 
     macos-mamba:
         needs: [pre-commit, cppcheck]
