Add test in CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -239,6 +239,7 @@ jobs:
                       -GNinja \
                       -DCMAKE_BUILD_TYPE=Release \
                       -DWITH_MPI=ON \
+                      -DWITH_PETSC=ON \
                       -DBUILD_DEMOS=ON \
                       -DBUILD_TESTS=ON
 
@@ -247,6 +248,7 @@ jobs:
               run: |
                   cmake --build build --target finite-volume-advection-2d --parallel 4
                   cmake --build build --target finite-volume-burgers --parallel 4
+                  cmake --build build --target finite-volume-heat --parallel 4
 
             - name: MPI test finite-volume-advection-2d
               shell: bash -l {0}
@@ -279,6 +281,20 @@ jobs:
                   python ../python/compare.py burgers_2D_size_1_ite_ burgers_2D_size_3_ite_ --start 1 --end 19
                   python ../python/compare.py burgers_2D_size_1_ite_ burgers_2D_size_4_ite_ --start 1 --end 19
                   python ../python/compare.py burgers_2D_size_1_ite_ burgers_2D_size_6_ite_ --start 1 --end 19
+
+            - name: MPI test finite-volume-heat
+              shell: bash -l {0}
+              run: |
+                  cd build
+                  set -e  # Stop on first failure
+                  mpiexec -n 1 ./demos/FiniteVolume/finite-volume-heat --Tf 0.1 --max-level 9
+                  mpiexec -n 2 ./demos/FiniteVolume/finite-volume-heat --Tf 0.1 --max-level 9
+                  mpiexec -n 3 ./demos/FiniteVolume/finite-volume-heat --Tf 0.1 --max-level 9
+                  mpiexec -n 4 ./demos/FiniteVolume/finite-volume-heat --Tf 0.1 --max-level 9
+                  ls
+                  python ../python/compare.py heat_2D_size_1_ite_ heat_2D_size_2_ite_ --start 1 --end 9
+                  python ../python/compare.py heat_2D_size_1_ite_ heat_2D_size_3_ite_ --start 1 --end 9
+                  python ../python/compare.py heat_2D_size_1_ite_ heat_2D_size_4_ite_ --start 1 --end 9
 
     macos-mamba:
         needs: [pre-commit, cppcheck]
