ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -297,7 +297,7 @@ jobs:
                   GLIBC_TUNABLES: "glibc.malloc.tcache_count=0"
               run: |
                   cd build
-                  # set -e  # Stop on first failure
+                  set -e  # Stop on first failure
                   # The MUMPS conda package is compiled with OpenMP. We set the number of threads to 1 to have deterministic output.
                   export OMP_NUM_THREADS=1
                   export OMP_DYNAMIC=FALSE
